id: I55AA3BED
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T08:37:38+00:00'
last_modified: '2022-06-08T07:04:16.337965+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5102
  title: ཕྱོགས་ཐམས་ཅད་ལས་རྣམ་པར་རྒྱལ་བ་རྡོ་རྗེ་འཆང་དངོས་ཀུན་མཁྱེན་བླ་མ་བཀྲ་ཤིས་བསྟན་པ་རབ་རྒྱས་ཀྱི་བསྔགས་བརྗོད་གཡས་འཁྱིལ་དུང་གི་རང་སྒྲ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    FF7D:
      image_group_id: I3CN5104
      title: ''
      total_pages: 220
      order: 1
      base_file: FF7D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
