id: P006818
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5102
  title: ཕྱོགས་ཐམས་ཅད་ལས་རྣམ་པར་རྒྱལ་བ་རྡོ་རྗེ་འཆང་དངོས་ཀུན་མཁྱེན་བླ་མ་བཀྲ་ཤིས་བསྟན་པ་རབ་རྒྱས་ཀྱི་བསྔགས་བརྗོད་གཡས་འཁྱིལ་དུང་གི་རང་སྒྲ།
  author: ''
  volumes: {}
